from sqlalchemy import Column, Integer, String, ForeignKey
from sqlalchemy.orm import relationship
from app.database import Base

class Service(Base):
    __tablename__ = "services"

    id = Column(Integer, primary_key=True, index=True)
    category_id = Column(Integer, ForeignKey("categories.id", ondelete="CASCADE"), nullable=False)

    name = Column(String, nullable=False)
    description = Column(String)

    category = relationship("Category", back_populates="services")

    listings = relationship("Listing", back_populates="service", cascade="all, delete")
    requests = relationship("Request", back_populates="service", cascade="all, delete")

"""add listing request quote tables fix

Revision ID: 22c2a255481e
Revises: 556cdc86d422
Create Date: 2025-07-10 21:04:11.952120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22c2a255481e'
down_revision: Union[str, Sequence[str], None] = '556cdc86d422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
