"""Add on delete cascade to booking foreign key

Revision ID: 67b53613dc92
Revises: 00df1d75aa83
Create Date: 2025-07-23 15:36:17.961347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67b53613dc92'
down_revision: Union[str, Sequence[str], None] = '00df1d75aa83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add the column as nullable
    op.add_column('bookings', sa.Column('listing_id', sa.Integer(), nullable=True))

    # 2. Backfill the column if possible (set to a valid listing_id or delete orphaned bookings)
    # If you can't backfill, you may need to delete rows with NULL quote_id or listing_id:
    # op.execute("DELETE FROM bookings WHERE listing_id IS NULL")
    # (Or set a default value if appropriate)

    # 3. Alter the column to NOT NULL
    op.alter_column('bookings', 'listing_id', nullable=False)

    # 4. Add the foreign key constraint with ON DELETE CASCADE
    op.create_foreign_key(
        'fk_bookings_listing_id_listings',
        'bookings', 'listings',
        ['listing_id'], ['id'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_bookings_listing_id_listings', 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'listing_id')
    # ### end Alembic commands ###
