"""remove unique from review table on booking id

Revision ID: 7ca89b76835e
Revises: 5ad538a81dff
Create Date: 2025-07-29 16:08:37.776691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ca89b76835e'
down_revision: Union[str, Sequence[str], None] = '5ad538a81dff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('reviews_booking_id_key'), 'reviews', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('reviews_booking_id_key'), 'reviews', ['booking_id'])
    # ### end Alembic commands ###
