"""Add profile_picture to Profile

Revision ID: 9a187efd6387
Revises: e3e8888f036f
Create Date: 2025-07-22 17:28:10.437326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a187efd6387'
down_revision: Union[str, Sequence[str], None] = 'e3e8888f036f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'quote_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'provider_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'has_review',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('bookings_customer_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_provider_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'users', ['customer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bookings', 'users', ['provider_id'], ['id'], ondelete='CASCADE')
    op.add_column('profiles', sa.Column('profile_picture', sa.String(), nullable=True))
    op.alter_column('profiles', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('profiles', 'bio',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'bio',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('profiles', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('profiles', 'profile_picture')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_provider_id_fkey'), 'bookings', 'users', ['provider_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('bookings_customer_id_fkey'), 'bookings', 'users', ['customer_id'], ['id'], ondelete='SET NULL')
    op.alter_column('bookings', 'has_review',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('bookings', 'provider_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'quote_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
